"""Initial Migration

Revision ID: 01124da49ef6
Revises: 6c61716457a3
Create Date: 2019-03-04 15:30:52.085628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01124da49ef6'
down_revision = '6c61716457a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'dislikes')
    op.drop_column('blogs', 'likes')
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_blog_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_column('comments', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_blog_fkey', 'comments', 'blogs', ['blog'], ['id'])
    op.drop_column('comments', 'blog_id')
    op.add_column('blogs', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
