"""third Migration

Revision ID: 80dba82291bb
Revises: 87bf2269a8b1
Create Date: 2019-02-28 10:20:26.194586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dba82291bb'
down_revision = '87bf2269a8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_content', sa.String(length=1000), nullable=True))
    op.add_column('pitches', sa.Column('pitch_title', sa.String(), nullable=True))
    op.drop_column('pitches', 'pitches_title')
    op.drop_column('pitches', 'pitches_contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitches_contents', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitches_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch_title')
    op.drop_column('pitches', 'pitch_content')
    # ### end Alembic commands ###
