"""Initial Migration

Revision ID: a4761f431940
Revises: 80dba82291bb
Create Date: 2019-02-28 17:16:10.586139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4761f431940'
down_revision = '80dba82291bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
